# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'depromeet-10-5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for depromeet-10-5
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'SnapKit'
    pod 'SwiftLint'

end
