# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'depromeet-10-5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for depromeet-10-5
    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'
    pod 'Alamofire', '~> 5.4'
    pod 'ObjectMapper', '~> 3.5'
    pod 'SnapKit', '~> 5.0.0'
    pod 'SwiftLint'

end
